title: Vedtak og profesjon  - Utforskende AQL 
path: "."
files: 
  - profesjon_vedtak.xml 
aqls: 
  - title: Profesjon_utforsker_nested_contains 
    description: Utforsker muligheten for å angi mer spesifikk CONTAINS. NB! Denne fungere rett og slett ikke! 
    aql: "SELECT
    a_e/data[at0001]/items[openEHR-EHR-CLUSTER.individual_professional_dips.v1 and name/value='Forlopskoordinator']/items[openEHR-EHR-CLUSTER.person_name_dips.v1]/items[at0001]/value/value AS forlopskoordinator,
    a_e_2/data[at0001]/items[openEHR-EHR-CLUSTER.individual_professional_dips.v1 and name/value='Ansvarlig spesialist']/items[openEHR-EHR-CLUSTER.person_name_dips.v1]/items[at0001]/value/value AS ansvarligspesialist,
    a_e_3/data[at0001]/items[openEHR-EHR-CLUSTER.individual_professional_dips.v1 and name/value='Ansvarlig behandler']/items[openEHR-EHR-CLUSTER.person_name_dips.v1]/items[at0001]/value/value AS ansvarligbehandler
FROM
    COMPOSITION c
        CONTAINS (ADMIN_ENTRY a_e[openEHR-EHR-ADMIN_ENTRY.administrative_container_dips.v1]
            CONTAINS CLUSTER c1[archetype_node_id = 'openEHR-EHR-CLUSTER.individual_professional_dips.v1'
            AND name/value = 'Forlopskoordinator']
        AND ADMIN_ENTRY a_e_2[openEHR-EHR-ADMIN_ENTRY.administrative_container_dips.v1]
            CONTAINS CLUSTER c2[archetype_node_id = 'openEHR-EHR-CLUSTER.individual_professional_dips.v1'
            AND name/value = 'Ansvarlig spesialist']
        AND ADMIN_ENTRY a_e_3[openEHR-EHR-ADMIN_ENTRY.administrative_container_dips.v1]
            CONTAINS CLUSTER c3[archetype_node_id = 'openEHR-EHR-CLUSTER.individual_professional_dips.v1'
            AND name/value = 'Ansvarlig behandler'])
LIMIT 20"
  - title: Fungerende fra EHR Craft 
    description: CONTAINS er korrekt , men permutasjonenen er mange 
    aql: "SELECT
    c1/items[openEHR-EHR-CLUSTER.person_name_dips.v1]/items[at0001]/value/value AS forlopskoordinator,
    c2/items[openEHR-EHR-CLUSTER.person_name_dips.v1]/items[at0001]/value/value AS ansvarligspesialist,
    c3/items[openEHR-EHR-CLUSTER.person_name_dips.v1]/items[at0001]/value/value AS ansvarligbehandler
FROM
    COMPOSITION c
        CONTAINS ADMIN_ENTRY a_e[openEHR-EHR-ADMIN_ENTRY.administrative_container_dips.v1]
            CONTAINS (CLUSTER c1[archetype_node_id = 'openEHR-EHR-CLUSTER.individual_professional_dips.v1'
            AND name/value = 'Forlopskoordinator']
            AND CLUSTER c2[archetype_node_id = 'openEHR-EHR-CLUSTER.individual_professional_dips.v1'
            AND name/value = 'Ansvarlig spesialist']
            AND CLUSTER c3[archetype_node_id = 'openEHR-EHR-CLUSTER.individual_professional_dips.v1'
            AND name/value = 'Ansvarlig behandler'])"
