= Example blood pressure 

== Background 
This is a follow up from case1-permutations. In this example we are using `openEHR-EHR-OBSERVATION.blood_pressure.v1`. 
The purpose is to examine how repeating observations and events in a _COMPOSITION_ affects AQL. 

The structure of the _COMPOSITION_ is outlined below and the full instance is attached as `example_bp.comp.(json|xml)`. 

[source]
----
1.0 Blood pressure 
        origin:     20:00
1.1 POINT_EVENT
        time:       20:05
        systolic:   100
        diastolic:  90
1.2 POINT_EVENT
        time:       20:10
        systolic:   101
        diastolic:  91
1.3 PROTOCOL
        cuff:       Adult thigh
2.0 Blood pressure
        origin:     20:15
2.1 POINT_EVENT
        time:       20:20
        systolic:   102
        diastolic:  92
2.3 PROTOCOL
        cuff:       Large adult 
----




NOTE: The units are removed. They will not change the example and the outputs. 

// The following composition UIDs may be used when testing: 

// BuenosAires id:: bfc1fdda-3564-41d9-97fc-397427b0b37c::default::1

// VT-SELECTA id:: 78433b24-4ae6-4bf8-8aaa-9f247acc131c::91215053-854b-45b8-bb2a-3b0d255858d1::1


== Blood pressure case 1 
In the following we provide to approaches : 

. <<bp.aql.1>> - which gives *"WRONG"* output.

. <<bp.aql.2>> which gives the *expected* output 

[[bp.aql.1]]
=== AQL 1 - the naive approach



[source]
----
SELECT
    o/data[at0001]/origin/value as Origin, 
    o/data[at0001]/events[at0006]/time/value as EventTime,
    o/data[at0001]/events[at0006]/data[at0003]/items[at0004]/value/magnitude as Systolic,
    o/data[at0001]/events[at0006]/data[at0003]/items[at0005]/value/magnitude as Diastolic,
    o/protocol[at0011]/items[at0013]/value/value as Cuff
         
FROM Composition c   
CONTAINS OBSERVATION o[openEHR-EHR-OBSERVATION.blood_pressure.v1]  
WHERE c/uid/value = '78433b24-4ae6-4bf8-8aaa-9f247acc131c::91215053-854b-45b8-bb2a-3b0d255858d1::1'
----


The openEHR resultset for this AQL is provided as `resultset_aql_1.(json|xml)`. Below is the table summary of the result. 

.Case 1 - the naive resultset 
[cols="1,3,3,2,2,2", options="header"]
|====
| # | Origin | EventTime | Systolic | Diastolic | Mansjett
|1 | 20:00  | 20:05 | 100 | 90 | Adult thigh
|2 | 20:00 | 20:10 | 100 | 90 | Adult thigh 
|3 | 20:00 | 20:05 | 101|90|Adult thigh 
|4 | 20:00 | 20:10 | 101|90 |Adult thigh 
|5 | 20:00 | 20:05| 100|91|Adult thigh 
|6 | 20:00 | 20:10 | 100| 91|Adult thigh 
|7 | 20:00 | 20:05 | 101 |91 |Adult thigh 
|8 | 20:00 | 20:10 | 101 |91 |Adult thigh 
|9 | 20:15| 20:20 | 102 | 92 | Large adult 
|====

CAUTION: This output is correct. It seems like it is 9 measurements. But in fact we have only 3. 

==== Array based resultset 
This is an update `23.april 2019` where we explore the possibility to return array for paths with multiple results. For the AQL above we see that the first observation has two point_events. For each of the paths in the tree we return an array. The resultset is given in the table below. 

.Case 1.1 - the array based resultset 
[cols="1,3,3,2,2,2", options="header"]
|====
| # | Origin | EventTime | Systolic | Diastolic | Mansjett
| 1 | 20:00  | [20:05, 20:10] | [100,101]| [90, 91] | Adult thigh
| 2 | 20:15 | 20:20 | 102 | 92 | Large adult
|====

*What if* it was only one of the point_events with diastolic? Then there would be only one match (and no array). In the table below we simulate this by letting only the second point_event having a diastolic value. As you see there is only one primitiv here and you can't tell which point event it is bound to. To be sure you have to make your query more explicit, ie. as shown in AQL 2 with POINT_EVENT.
.Case 1.2 - Where first blood pressure had no diastolic 
[cols="1,3,3,2,2,2", options="header"]
|====
| # | Origin | EventTime | Systolic | Diastolic | Mansjett
| 1 | 20:00  | [20:05, 20:10] | [100,101]| 91 | Adult thigh
| 2 | 20:15 | 20:20 | 102 | 92 | Large adult
|====



[[bp.aql.2]]
=== AQL 2 - with POINT_EVENT
This example gives the expected output for this kind of query on the given _COMPOSITION_. We did 3 measurements and they are all present with their respective values.
[source]
----
SELECT
    o/data[at0001]/origin/value as Origin,
    pe/time/value as EventTime,
    pe/data[at0003]/items[at0004]/value/magnitude as Systolic,
    pe/data[at0003]/items[at0005]/value/magnitude as Diastolic,
    o/protocol[at0011]/items[at0013]/value/value as Cuff
       
FROM Composition c   
    CONTAINS OBSERVATION o[openEHR-EHR-OBSERVATION.blood_pressure.v1]  
    CONTAINS POINT_EVENT pe 
WHERE c/uid/value = '78433b24-4ae6-4bf8-8aaa-9f247acc131c::91215053-854b-45b8-bb2a-3b0d255858d1::1'   
----

The openEHR resultset for this AQL is provided as `resultset_aql_2.(json|xml)`.Below is the table summary of the result. 
    
[cols="1,3,3,2,2,2", options="header"]
|====
| # | Origin | EventTime | Systolic | Diastolic | Mansjett
|1 | 20:00  | 20:05 | 100 | 90 | Adult thigh
|4 | 20:00 | 20:10 | 101|90 |Adult thigh 
|9 |20:15| 20:20 | 102 | 92 | Large adult 
|====

The openEHR resultset for this AQL is provided as `resultset_aql_2.(json|xml)`.Below is the table summary of the result. 

NOTE: This is correct and compared to <<bp.aql.1>> we see that only row 1,4 and 9 is returned.



  
    